name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write # for creating git tags during publish

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    # Run only on manual dispatch OR on merge of the Release PR (title/message contains 'Version Packages')
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'Version Packages')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build & Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$NPM_TOKEN" ]; then echo "NPM_TOKEN not set"; exit 1; fi
          pnpm release

      - name: Summary
        run: echo "Publish step completed (trigger: ${{ github.event_name }})"
